// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using projectTest.Models;

#nullable disable

namespace projectTest.Migrations
{
    [DbContext(typeof(dbContext))]
    [Migration("20241205073748_20241205_addApplyStatuColumn")]
    partial class _20241205_addApplyStatuColumn
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("projectTest.Models.DepBudget", b =>
                {
                    b.Property<decimal>("budget")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("budget_remain")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("depcname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("depid")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("depno")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("fundname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("fundno")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("leader")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("leaderid")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("projectno")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sourcetype")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("DepBudget");
                });

            modelBuilder.Entity("projectTest.Models.FullTime_order", b =>
                {
                    b.Property<string>("FullTime_orderNo")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("ApplicantName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Application")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("ApplicationOffice")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<DateTime>("ApplicationTime")
                        .HasColumnType("datetime");

                    b.Property<string>("Birthday")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("EducationLevel")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("EmployedEndDate")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("EmployedName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("EmployedStartDate")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("ID")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("ResignDate")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Salary")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("SalaryChangeDate")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("SalaryChangeReason")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("SalaryGrade")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("isApplyRenewal")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)")
                        .HasDefaultValue("0");

                    b.Property<string>("isApplyResignation")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)")
                        .HasDefaultValue("0");

                    b.Property<string>("isApplySalaryChange")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)")
                        .HasDefaultValue("0");

                    b.HasKey("FullTime_orderNo");

                    b.ToTable("FullTime_order");
                });

            modelBuilder.Entity("projectTest.Models.FullTime_order_detail", b =>
                {
                    b.Property<string>("FullTime_orderNo")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("AccountNo")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("CommissionName")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("LeaderName")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("PlanEndDate")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("PlanName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PlanNo")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("PlanStartDate")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("projtype")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.HasKey("FullTime_orderNo", "AccountNo");

                    b.ToTable("FullTime_order_detail");
                });

            modelBuilder.Entity("projectTest.Models.ManagerAuthority", b =>
                {
                    b.Property<string>("Authority")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("EmployeeNo")
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.HasKey("Authority", "EmployeeNo");

                    b.ToTable("ManagerAuthority");
                });

            modelBuilder.Entity("projectTest.Models.PartTime_order", b =>
                {
                    b.Property<string>("PartTime_orderNo")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("AccountNo")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("ApplicantName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Application")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("ApplicationOffice")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<DateTime>("ApplicationTime")
                        .HasColumnType("datetime");

                    b.Property<string>("Birthday")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("CommissionName")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("EducationLevel")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("EmployedEndDate")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("EmployedName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("EmployedStartDate")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("ID")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("IsTechPerson")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("LeaderName")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("PlanEndDate")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("PlanName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PlanNo")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("PlanStartDate")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("ResignDate")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Salary")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("SalaryCategory")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("SalaryChangeDate")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("StudyStatus")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("StudyStatusMemo")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("isApplyRenewal")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)")
                        .HasDefaultValue("0");

                    b.Property<string>("isApplyResignation")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)")
                        .HasDefaultValue("0");

                    b.Property<string>("isApplySalaryChange")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)")
                        .HasDefaultValue("0");

                    b.Property<string>("phone")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("projtype")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.HasKey("PartTime_orderNo");

                    b.ToTable("PartTime_order");
                });

            modelBuilder.Entity("projectTest.Models.ProjectBudget", b =>
                {
                    b.Property<decimal>("budget")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("budget_remain")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("com")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("comname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("enddate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("extenddate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("fundname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("fundno")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("leadercard")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("leadername")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pjttype")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("projectname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("projectno")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("projno")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sourcetype")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("startdate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("ProjectBudget");
                });

            modelBuilder.Entity("projectTest.Models.Studentinfo", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("birthday")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("department")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pclass")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sclass")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("studentID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("Studentinfo");
                });

            modelBuilder.Entity("projectTest.Models.FullTime_order_detail", b =>
                {
                    b.HasOne("projectTest.Models.FullTime_order", "FullTimeOrder")
                        .WithMany("OrderDetails")
                        .HasForeignKey("FullTime_orderNo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_FullTime_Order_detail_FullTime_Order");

                    b.Navigation("FullTimeOrder");
                });

            modelBuilder.Entity("projectTest.Models.FullTime_order", b =>
                {
                    b.Navigation("OrderDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
